SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://docker.awsapps.com/start
        Accounts:
            313121495448:
                Name: uc
                Roles:
                    OffloadReadOnly:
                        Profile: uc
                    OffloadElevated:
                        Profile: uc:admin
                        Via: arn:aws:iam::313121495448:role/OffloadReadOnly
            447924746603:
                Name: ucs
                Roles:
                    OffloadReadOnly:
                        Profile: ucs
                    OffloadElevated:
                        Profile: ucs:admin
                        Via: arn:aws:iam::447924746603:role/OffloadReadOnly
            318510287843:
                Name: bw
                Roles:
                    OffloadReadOnly:
                        Profile: bw
                    OffloadElevated:
                        Profile: bw:admin
                        Via: arn:aws:iam::318510287843:role/OffloadReadOnly
            539272219385:
                Name: bws
                Roles:
                    OffloadReadOnly:
                        Profile: bws
                    OffloadElevated:
                        Profile: bws:admin
                        Via: arn:aws:iam::539272219385:role/OffloadReadOnly
            622992712626:
                Name: sw
                Roles:
                    OffloadReadOnly:
                        Profile: sw
                    OffloadElevated:
                        Profile: sw:admin
                        Via: arn:aws:iam::622992712626:role/OffloadReadOnly
            602326734147:
                Name: sws
                Roles:
                    OffloadReadOnly:
                        Profile: sws
                    OffloadElevated:
                        Profile: sws:admin
                        Via: arn:aws:iam::602326734147:role/OffloadReadOnly
            300042230143:
                Name: tiaa
                Roles:
                    OffloadReadOnly:
                        Profile: tiaa
                    OffloadElevated:
                        Profile: tiaa:admin
                        Via: arn:aws:iam::300042230143:role/OffloadReadOnly
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: exec
UrlExecCommand:
    - /usr/bin/open
    - -a
    - /Applications/Firefox.app
    - -n
    - --args
    - --profile
    - /Users/lanwen/Library/Application Support/Firefox/Profiles/cP89VZaw.Profile 1
    - --new-tab
    - "%s"
LogLevel: error
SecureStore: 1password
OnePassword:
    Vault: AWS
    Account: kirill.merkushev@docker.com
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountIdPad }}:{{ .RoleName }}"
FullTextSearch: true
